server:
  port: 8081
spring:
  application:
    name: ultraPlexMovieBookingSystem
  security:
    user:
      name: bookingUser
      password: bookingPassword
  datasource:
    url: jdbc:postgresql://localhost:5432/ultraplexDb
    username: postgres
    password: admin22
  jpa:
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true